/*
Generated by Yara-Rules
On 09-06-2019
*/
include "./Webshells/WShell_APT_Laudanum.yar"
include "./Webshells/WShell_ASPXSpy.yar"
include "./Webshells/Wshell_ChineseSpam.yar"
include "./Webshells/Wshell_fire2013.yar"
include "./Webshells/WShell_PHP_Anuna.yar"
include "./Webshells/WShell_THOR_Webshells.yar"
